services:
  - type: web
    name: inventory-system
    env: python
    buildCommand: pip install -r inventory_system/requirements.txt
    startCommand: cd inventory_system && gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
