services:
  - type: web
    name: inventory-system
    env: python
    buildCommand: cd inventory_system && pip install -r requirements.txt
    startCommand: cd inventory_system && gunicorn -w 2 -b 0.0.0.0:10000 run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
